export const customProgressions = [
  {
    genre: "Neo Soul",
    chordProgressions: [
      {
        id: 1,
        chords: [
          { chord: "V", quality: "m11", midiKeys: [60, 63, 67, 70, 74, 77] },
          { chord: "V", quality: "m7", midiKeys: [60, 63, 67, 70] },
          { chord: "I", quality: "min9", midiKeys: [60, 63, 67, 70, 74] },
          { chord: "IV", quality: "maj9", midiKeys: [60, 64, 67, 71, 74] },
        ],
      },
      {
        id: 2,
        chords: [
          { chord: "ii", quality: "m11", midiKeys: [60, 63, 67, 70, 74, 77] },
          { chord: "iii", quality: "maj9", midiKeys: [60, 64, 67, 71, 74] },
          { chord: "IV", quality: "m7", midiKeys: [60, 63, 67, 70] },
          { chord: "ii", quality: "7", midiKeys: [60, 64, 67, 70] },
        ],
      },
      {
        id: 3,
        chords: [
          { chord: "vi", quality: "13", midiKeys: [60, 64, 67, 70, 74, 81] },
          { chord: "V", quality: "7", midiKeys: [60, 64, 67, 70] },
          { chord: "iii", quality: "m6", midiKeys: [60, 63, 67, 69] },
          { chord: "V", quality: "maj9", midiKeys: [60, 64, 67, 71, 74] },
        ],
      },
      {
        id: 4,
        chords: [
          { chord: "vi", quality: "maj9", midiKeys: [60, 64, 67, 71, 74] },
          { chord: "ii", quality: "6", midiKeys: [60, 64, 67, 69] },
          { chord: "ii", quality: "min9", midiKeys: [60, 63, 67, 70, 74] },
          { chord: "V", quality: "7", midiKeys: [60, 64, 67, 70] },
        ],
      },
      {
        id: 5,
        chords: [
          { chord: "vii", quality: "69", midiKeys: [60, 64, 67, 69, 74] },
          { chord: "IV", quality: "13", midiKeys: [60, 64, 67, 70, 74, 81] },
          { chord: "vii", quality: "min9", midiKeys: [60, 63, 67, 70, 74] },
          { chord: "ii", quality: "m6", midiKeys: [60, 63, 67, 69] },
        ],
      },
    ],
  },
  {
    genre: "Inspirational",
    chordProgressions: [
      {
        id: 1,
        chords: [
          { chord: "iii", quality: "m", midiKeys: [60, 63, 67] },
          { chord: "ii", quality: "6", midiKeys: [60, 64, 67, 69] },
          { chord: "IV", quality: "maj", midiKeys: [60, 64, 67] },
          { chord: "vi", quality: "4", midiKeys: [60, 65, 67] },
        ],
      },
      {
        id: 2,
        chords: [
          { chord: "ii", quality: "maj7", midiKeys: [60, 64, 67, 71] },
          { chord: "vii", quality: "6", midiKeys: [60, 64, 67, 69] },
          { chord: "iii", quality: "2", midiKeys: [60, 62, 67] },
          { chord: "vi", quality: "m7", midiKeys: [60, 63, 67, 70] },
        ],
      },
      {
        id: 3,
        chords: [
          { chord: "ii", quality: "add9", midiKeys: [60, 64, 67, 74] },
          { chord: "vii", quality: "6", midiKeys: [60, 64, 67, 69] },
          { chord: "ii", quality: "4", midiKeys: [60, 65, 67] },
          { chord: "iii", quality: "maj7", midiKeys: [60, 64, 67, 71] },
        ],
      },
      {
        id: 4,
        chords: [
          { chord: "vii", quality: "m7", midiKeys: [60, 63, 67, 70] },
          { chord: "IV", quality: "add9", midiKeys: [60, 64, 67, 74] },
          { chord: "vii", quality: "maj", midiKeys: [60, 64, 67] },
          { chord: "iii", quality: "2", midiKeys: [60, 62, 67] },
        ],
      },
      {
        id: 5,
        chords: [
          { chord: "iii", quality: "6", midiKeys: [60, 64, 67, 69] },
          { chord: "ii", quality: "maj7", midiKeys: [60, 64, 67, 71] },
          { chord: "IV", quality: "add9", midiKeys: [60, 64, 67, 74] },
          { chord: "vii", quality: "maj9", midiKeys: [60, 64, 67, 71, 74] },
        ],
      },
    ],
  },
  {
    genre: "Funk",
    chordProgressions: [
      {
        id: 1,
        chords: [
          { chord: "vii", quality: "m9", midiKeys: [60, 63, 67, 70, 74] },
          { chord: "IV", quality: "9", midiKeys: [60, 64, 67, 70, 74] },
          { chord: "V", quality: "7", midiKeys: [60, 64, 67, 70] },
          { chord: "iii", quality: "6", midiKeys: [60, 64, 67, 69] },
        ],
      },
      {
        id: 2,
        chords: [
          { chord: "I", quality: "m7", midiKeys: [60, 63, 67, 70] },
          {
            chord: "IV",
            quality: "9sharp11",
            midiKeys: [60, 64, 67, 70, 74, 78],
          },
          { chord: "vii", quality: "13", midiKeys: [60, 64, 67, 70, 74, 81] },
          { chord: "ii", quality: "6", midiKeys: [60, 64, 67, 69] },
        ],
      },
      {
        id: 3,
        chords: [
          { chord: "iii", quality: "m7", midiKeys: [60, 63, 67, 70] },
          {
            chord: "V",
            quality: "9sharp11",
            midiKeys: [60, 64, 67, 70, 74, 78],
          },
          { chord: "I", quality: "7", midiKeys: [60, 64, 67, 70] },
          { chord: "vi", quality: "13", midiKeys: [60, 64, 67, 70, 74, 81] },
        ],
      },
      {
        id: 4,
        chords: [
          { chord: "vi", quality: "7sharp9", midiKeys: [60, 64, 67, 70, 75] },
          { chord: "I", quality: "6", midiKeys: [60, 64, 67, 69] },
          { chord: "iii", quality: "13", midiKeys: [60, 64, 67, 70, 74, 81] },
          { chord: "I", quality: "7sus4", midiKeys: [60, 65, 67, 70] },
        ],
      },
      {
        id: 5,
        chords: [
          { chord: "iii", quality: "7sus4", midiKeys: [60, 65, 67, 70] },
          { chord: "vii", quality: "m9", midiKeys: [60, 63, 67, 70, 74] },
          { chord: "ii", quality: "m7", midiKeys: [60, 63, 67, 70] },
          { chord: "ii", quality: "7b9", midiKeys: [60, 64, 67, 70, 73] },
        ],
      },
    ],
  },
  {
    genre: "Country",
    chordProgressions: [
      {
        id: 1,
        chords: [
          { chord: "ii", quality: "m", midiKeys: [60, 63, 67] },
          { chord: "ii", quality: "maj7", midiKeys: [60, 64, 67, 71] },
          { chord: "V", quality: "maj", midiKeys: [60, 64, 67] },
          { chord: "V", quality: "add9", midiKeys: [60, 64, 67, 74] },
        ],
      },
      {
        id: 2,
        chords: [
          { chord: "vii", quality: "m7", midiKeys: [60, 63, 67, 70] },
          { chord: "I", quality: "7", midiKeys: [60, 64, 67, 70] },
          { chord: "vi", quality: "2", midiKeys: [60, 62, 67] },
          { chord: "ii", quality: "6", midiKeys: [60, 64, 67, 69] },
        ],
      },
      {
        id: 3,
        chords: [
          { chord: "V", quality: "maj7", midiKeys: [60, 64, 67, 71] },
          { chord: "I", quality: "sus4", midiKeys: [60, 65, 67] },
          { chord: "I", quality: "sus2", midiKeys: [60, 62, 67] },
          { chord: "vii", quality: "maj", midiKeys: [60, 64, 67] },
        ],
      },
      {
        id: 4,
        chords: [
          { chord: "vii", quality: "m7", midiKeys: [60, 63, 67, 70] },
          { chord: "iii", quality: "maj7", midiKeys: [60, 64, 67, 71] },
          { chord: "iii", quality: "sus4", midiKeys: [60, 65, 67] },
          { chord: "iii", quality: "7", midiKeys: [60, 64, 67, 70] },
        ],
      },
      {
        id: 5,
        chords: [
          { chord: "ii", quality: "m", midiKeys: [60, 63, 67] },
          { chord: "I", quality: "sus4", midiKeys: [60, 65, 67] },
          { chord: "iii", quality: "2", midiKeys: [60, 62, 67] },
          { chord: "V", quality: "add9", midiKeys: [60, 64, 67, 74] },
        ],
      },
    ],
  },
  {
    genre: "Ambient",
    chordProgressions: [
      {
        id: 1,
        chords: [
          { chord: "vii", quality: "m9", midiKeys: [60, 63, 67, 70, 74] },
          { chord: "vi", quality: "m11", midiKeys: [60, 63, 67, 70, 74, 77] },
          { chord: "iii", quality: "m7", midiKeys: [60, 63, 67, 70] },
          { chord: "vi", quality: "maj9", midiKeys: [60, 64, 67, 71, 74] },
        ],
      },
      {
        id: 2,
        chords: [
          { chord: "vi", quality: "dim", midiKeys: [60, 63, 66] },
          { chord: "V", quality: "m7", midiKeys: [60, 63, 67, 70] },
          { chord: "I", quality: "mmaj9", midiKeys: [60, 63, 67, 71, 74] },
          { chord: "I", quality: "maj11", midiKeys: [60, 67, 71, 74, 77] },
        ],
      },
      {
        id: 3,
        chords: [
          { chord: "iii", quality: "mmaj9", midiKeys: [60, 63, 67, 71, 74] },
          { chord: "iii", quality: "maj11", midiKeys: [60, 67, 71, 74, 77] },
          { chord: "IV", quality: "m11", midiKeys: [60, 63, 67, 70, 74, 77] },
          { chord: "IV", quality: "m9", midiKeys: [60, 63, 67, 70, 74] },
        ],
      },
      {
        id: 4,
        chords: [
          { chord: "vii", quality: "maj7", midiKeys: [60, 64, 67, 71] },
          { chord: "ii", quality: "maj9", midiKeys: [60, 64, 67, 71, 74] },
          { chord: "iii", quality: "m9", midiKeys: [60, 63, 67, 70, 74] },
          { chord: "iii", quality: "mmaj7", midiKeys: [60, 63, 67, 71] },
        ],
      },
      {
        id: 5,
        chords: [
          { chord: "V", quality: "mmaj7", midiKeys: [60, 63, 67, 71] },
          { chord: "vi", quality: "dim", midiKeys: [60, 63, 66] },
          { chord: "IV", quality: "m7", midiKeys: [60, 63, 67, 70] },
          { chord: "iii", quality: "maj7", midiKeys: [60, 64, 67, 71] },
        ],
      },
    ],
  },
];

export const chordRhythms = [
  {
    id: 1,
    name: "Pattern 1",
    notesLeft: [
      [
        {
          chordTone: 1,
          midi: 36,
          name: "C2",
          durationTicks: 260,
          timeTicks: 22,
          velocity: 0.5,
        },
        {
          chordTone: 2,
          midi: 48,
          name: "C3",
          durationTicks: 150,
          timeTicks: 393,
          velocity: 0.35,
        },
        {
          chordTone: 2,
          midi: 48,
          name: "C3",
          durationTicks: 145,
          timeTicks: 1128,
          velocity: 0.28,
        },
        {
          chordTone: 1,
          midi: 36,
          name: "C2",
          durationTicks: 203,
          timeTicks: 1251,
          velocity: 0.39,
        },
      ],

      [
        {
          chordTone: 1,
          midi: 38,
          name: "D2",
          durationTicks: 234,
          timeTicks: 2000,
          velocity: 0.15,
        },
        {
          chordTone: 2,
          midi: 50,
          name: "D3",
          durationTicks: 142,
          timeTicks: 2341,
          velocity: 0.38,
        },
        {
          chordTone: 2,
          midi: 50,
          name: "D3",
          durationTicks: 140,
          timeTicks: 3045,
          velocity: 0.33,
        },
      ],

      [
        {
          chordTone: 1,
          midi: 52,
          name: "E3",
          durationTicks: 142,
          timeTicks: 4261,
          velocity: 0.46,
        },

        {
          chordTone: 1,
          midi: 52,
          name: "E3",
          durationTicks: 145,
          timeTicks: 4970,
          velocity: 0.33,
        },
      ],

      [
        {
          chordTone: 1,
          midi: 53,
          name: "F3",
          durationTicks: 79,
          timeTicks: 3180,
          velocity: 0.25,
        },
        {
          chordTone: 2,
          midi: 53,
          name: "F3",
          durationTicks: 90,
          timeTicks: 7005,
          velocity: 0.23,
        },
      ],
    ],
    notesRight: [
      [
        {
          chordTone: 1,
          midi: 60,
          name: "C4",
          durationTicks: 85,
          timeTicks: 525,
          velocity: 0.47,
        },
        {
          chordTone: 2,
          midi: 64,
          name: "E4",
          durationTicks: 64,
          timeTicks: 528,
          velocity: 0.62,
        },
        {
          chordTone: 3,
          midi: 67,
          name: "G4",
          durationTicks: 59,
          timeTicks: 531,
          velocity: 0.42,
        },
        {
          chordTone: 1,
          midi: 64,
          name: "E4",
          durationTicks: 55,
          timeTicks: 898,
          velocity: 0.54,
        },
        {
          chordTone: 2,
          midi: 67,
          name: "G4",
          durationTicks: 56,
          timeTicks: 899,
          velocity: 0.46,
        },
        {
          chordTone: 3,
          midi: 60,
          name: "C4",
          durationTicks: 69,
          timeTicks: 900,
          velocity: 0.38,
        },
        {
          chordTone: 1,
          midi: 67,
          name: "G4",
          durationTicks: 84,
          timeTicks: 1270,
          velocity: 0.44,
        },
        {
          chordTone: 2,
          midi: 64,
          name: "E4",
          durationTicks: 75,
          timeTicks: 1271,
          velocity: 0.5,
        },
        {
          chordTone: 3,
          midi: 60,
          name: "C4",
          durationTicks: 76,
          timeTicks: 1276,
          velocity: 0.32,
        },
        {
          chordTone: 1,
          midi: 64,
          name: "E4",
          durationTicks: 93,
          timeTicks: 1642,
          velocity: 0.39,
        },
        {
          chordTone: 2,
          midi: 67,
          name: "G4",
          durationTicks: 93,
          timeTicks: 1649,
          velocity: 0.31,
        },
        {
          chordTone: 3,
          midi: 60,
          name: "C4",
          durationTicks: 92,
          timeTicks: 1653,
          velocity: 0.24,
        },
      ],

      [
        {
          chordTone: 1,
          midi: 62,
          name: "D4",
          durationTicks: 78,
          timeTicks: 1887,
          velocity: 0.4,
        },
        {
          chordTone: 2,
          midi: 69,
          name: "A4",
          durationTicks: 72,
          timeTicks: 1888,
          velocity: 0.46,
        },
        {
          chordTone: 3,
          midi: 65,
          name: "F4",
          durationTicks: 58,
          timeTicks: 1890,
          velocity: 0.46,
        },
        {
          chordTone: 1,
          midi: 62,
          name: "D4",
          durationTicks: 145,
          timeTicks: 2830,
          velocity: 0.44,
        },
        {
          chordTone: 2,
          midi: 69,
          name: "A4",
          durationTicks: 72,
          timeTicks: 2830,
          velocity: 0.47,
        },
        {
          chordTone: 3,
          midi: 65,
          name: "F4",
          durationTicks: 66,
          timeTicks: 2831,
          velocity: 0.51,
        },
        {
          chordTone: 1,
          midi: 62,
          name: "D4",
          durationTicks: 78,
          timeTicks: 2830,
          velocity: 0.45,
        },
        {
          chordTone: 2,
          midi: 69,
          name: "A4",
          durationTicks: 72,
          timeTicks: 2830,
          velocity: 0.51,
        },
        {
          chordTone: 3,
          midi: 65,
          name: "F4",
          durationTicks: 66,
          timeTicks: 2831,
          velocity: 0.54,
        },
        {
          chordTone: 1,
          midi: 69,
          name: "A4",
          durationTicks: 74,
          timeTicks: 3578,
          velocity: 0.57,
        },
        {
          chordTone: 2,
          midi: 62,
          name: "D4",
          durationTicks: 70,
          timeTicks: 3579,
          velocity: 0.49,
        },
        {
          chordTone: 3,
          midi: 65,
          name: "F4",
          durationTicks: 62,
          timeTicks: 3580,
          velocity: 0.62,
        },
      ],

      [
        {
          chordTone: 1,
          midi: 64,
          name: "E4",
          durationTicks: 74,
          timeTicks: 4757,
          velocity: 0.44,
        },
        {
          chordTone: 2,
          midi: 71,
          name: "B4",
          durationTicks: 69,
          timeTicks: 4748,
          velocity: 0.54,
        },
        {
          chordTone: 3,
          midi: 67,
          name: "G4",
          durationTicks: 59,
          timeTicks: 4754,
          velocity: 0.5,
        },
        {
          chordTone: 1,
          midi: 71,
          name: "B4",
          durationTicks: 75,
          timeTicks: 5098,
          velocity: 0.49,
        },
        {
          chordTone: 2,
          midi: 67,
          name: "G4",
          durationTicks: 75,
          timeTicks: 5098,
          velocity: 0.54,
        },
        {
          chordTone: 3,
          midi: 64,
          name: "E4",
          durationTicks: 79,
          timeTicks: 5101,
          velocity: 0.39,
        },
        {
          chordTone: 1,
          midi: 71,
          name: "B4",
          durationTicks: 97,
          timeTicks: 5463,
          velocity: 0.28,
        },
        {
          chordTone: 2,
          midi: 67,
          name: "G4",
          durationTicks: 81,
          timeTicks: 5484,
          velocity: 0.26,
        },
        {
          chordTone: 3,
          midi: 64,
          name: "E4",
          durationTicks: 81,
          timeTicks: 5484,
          velocity: 0.37,
        },
      ],

      [
        {
          chordTone: 1,
          midi: 65,
          name: "F4",
          durationTicks: 88,
          timeTicks: 5700,
          velocity: 0.39,
        },
        {
          chordTone: 2,
          midi: 69,
          name: "A4",
          durationTicks: 68,
          timeTicks: 5702,
          velocity: 0.51,
        },
        {
          chordTone: 3,
          midi: 72,
          name: "C5",
          durationTicks: 75,
          timeTicks: 5706,
          velocity: 0.5,
        },
        {
          chordTone: 1,
          midi: 65,
          name: "F4",
          durationTicks: 90,
          timeTicks: 6281,
          velocity: 0.47,
        },
        {
          chordTone: 2,
          midi: 72,
          name: "C5",
          durationTicks: 88,
          timeTicks: 6281,
          velocity: 0.57,
        },
        {
          chordTone: 3,
          midi: 69,
          name: "A4",
          durationTicks: 67,
          timeTicks: 6281,
          velocity: 0.54,
        },
        {
          chordTone: 1,
          midi: 72,
          name: "C5",
          durationTicks: 74,
          timeTicks: 6652,
          velocity: 0.63,
        },
        {
          chordTone: 2,
          midi: 65,
          name: "F4",
          durationTicks: 77,
          timeTicks: 6656,
          velocity: 0.54,
        },
        {
          chordTone: 3,
          midi: 69,
          name: "A4",
          durationTicks: 74,
          timeTicks: 6655,
          velocity: 0.62,
        },
        {
          chordTone: 1,
          midi: 65,
          name: "F4",
          durationTicks: 77,
          timeTicks: 6656,
          velocity: 0.31,
        },
        {
          chordTone: 2,
          midi: 53,
          name: "F3",
          durationTicks: 137,
          timeTicks: 6868,
          velocity: 0.23,
        },
        {
          chordTone: 3,
          midi: 65,
          name: "F4",
          durationTicks: 90,
          timeTicks: 7005,
          velocity: 0.51,
        },
        {
          chordTone: 1,
          midi: 72,
          name: "C5",
          durationTicks: 81,
          timeTicks: 7005,
          velocity: 0.63,
        },
        {
          chordTone: 2,
          midi: 69,
          name: "A4",
          durationTicks: 62,
          timeTicks: 7011,
          velocity: 0.61,
        },
        {
          chordTone: 3,
          midi: 65,
          name: "F4",
          durationTicks: 79,
          timeTicks: 7396,
          velocity: 0.47,
        },
        {
          chordTone: 1,
          midi: 72,
          name: "C5",
          durationTicks: 68,
          timeTicks: 7397,
          velocity: 0.57,
        },
        {
          chordTone: 2,
          midi: 69,
          name: "A4",
          durationTicks: 53,
          timeTicks: 7400,
          velocity: 0.54,
        },
        {
          chordTone: 3,
          midi: 72,
          name: "C5",
          durationTicks: 70,
          timeTicks: 7611,
          velocity: 0.63,
        },
        {
          chordTone: 1,
          midi: 65,
          name: "F4",
          durationTicks: 81,
          timeTicks: 7612,
          velocity: 0.54,
        },
        {
          chordTone: 2,
          midi: 69,
          name: "A4",
          durationTicks: 63,
          timeTicks: 7613,
          velocity: 0.62,
        },
      ],
    ],
  },
];

export const SAMPLER_INSTRUMENTS = {
  piano: {
    name: "Piano",
    samples: {
      A1: "A1.mp3",
      A2: "A2.mp3",
      A3: "A3.mp3",
      A4: "A4.mp3",
      A5: "A5.mp3",
      A6: "A6.mp3",
      A7: "A7.mp3",
      "A#1": "As1.mp3",
      "A#2": "As2.mp3",
      "A#3": "As3.mp3",
      "A#4": "As4.mp3",
      "A#5": "As5.mp3",
      "A#6": "As6.mp3",
      "A#7": "As7.mp3",
      B1: "B1.mp3",
      B2: "B2.mp3",
      B3: "B3.mp3",
      B4: "B4.mp3",
      B5: "B5.mp3",
      B6: "B6.mp3",
      B7: "B7.mp3",
      C1: "C1.mp3",
      C2: "C2.mp3",
      C3: "C3.mp3",
      C4: "C4.mp3",
      C5: "C5.mp3",
      C6: "C6.mp3",
      C7: "C7.mp3",
      C8: "C8.mp3",
      "C#1": "Cs1.mp3",
      "C#2": "Cs2.mp3",
      "C#3": "Cs3.mp3",
      "C#4": "Cs4.mp3",
      "C#5": "Cs5.mp3",
      "C#6": "Cs6.mp3",
      "C#7": "Cs7.mp3",
      D1: "D1.mp3",
      D2: "D2.mp3",
      D3: "D3.mp3",
      D4: "D4.mp3",
      D5: "D5.mp3",
      D6: "D6.mp3",
      D7: "D7.mp3",
      "D#1": "Ds1.mp3",
      "D#2": "Ds2.mp3",
      "D#3": "Ds3.mp3",
      "D#4": "Ds4.mp3",
      "D#5": "Ds5.mp3",
      "D#6": "Ds6.mp3",
      "D#7": "Ds7.mp3",
      E1: "E1.mp3",
      E2: "E2.mp3",
      E3: "E3.mp3",
      E4: "E4.mp3",
      E5: "E5.mp3",
      E6: "E6.mp3",
      E7: "E7.mp3",
      F1: "F1.mp3",
      F2: "F2.mp3",
      F3: "F3.mp3",
      F4: "F4.mp3",
      F5: "F5.mp3",
      F6: "F6.mp3",
      F7: "F7.mp3",
      "F#1": "Fs1.mp3",
      "F#2": "Fs2.mp3",
      "F#3": "Fs3.mp3",
      "F#4": "Fs4.mp3",
      "F#5": "Fs5.mp3",
      "F#6": "Fs6.mp3",
      "F#7": "Fs7.mp3",
      G1: "G1.mp3",
      G2: "G2.mp3",
      G3: "G3.mp3",
      G4: "G4.mp3",
      G5: "G5.mp3",
      G6: "G6.mp3",
      G7: "G7.mp3",
      "G#1": "Gs1.mp3",
      "G#2": "Gs2.mp3",
      "G#3": "Gs3.mp3",
      "G#4": "Gs4.mp3",
      "G#5": "Gs5.mp3",
      "G#6": "Gs6.mp3",
      "G#7": "Gs7.mp3",
    },
  },
  electricGuitar: {
    name: "Electric Guitar",
    samples: {
      A2: "A2.mp3",
      A3: "A3.mp3",
      A4: "A4.mp3",
      A5: "A5.mp3",
      C3: "C3.mp3",
      C4: "C4.mp3",
      C5: "C5.mp3",
      C6: "C6.mp3",
      "C#2": "Cs2.mp3",
      "D#3": "Ds3.mp3",
      "D#4": "Ds4.mp3",
      "D#5": "Ds5.mp3",
      E2: "E2.mp3",
      "F#2": "Fs2.mp3",
      "F#3": "Fs3.mp3",
      "F#4": "Fs4.mp3",
      "F#5": "Fs5.mp3",
    },
    // Add more instruments and their samples as needed...
  },
  electricBass: {
    name: "Bass Guitar",
    samples: {
      "A#1": "As1.mp3",
      "A#2": "As2.mp3",
      "A#3": "As3.mp3",
      "A#4": "As4.mp3",
      "C#1": "Cs1.mp3",
      "C#2": "Cs2.mp3",
      "C#3": "Cs3.mp3",
      "C#4": "Cs4.mp3",
      "C#5": "Cs5.mp3",
      E1: "E1.mp3",
      E2: "E2.mp3",
      E3: "E3.mp3",
      E4: "E4.mp3",
      G1: "G1.mp3",
      G2: "G2.mp3",
      G3: "G3.mp3",
      G4: "G4.mp3",
    },
    // Add more instruments and their samples as needed...
  },
  nylonGuitar: {
    name: "Classical Guitar",
    samples: {
      A2: "A2.mp3",
      A3: "A3.mp3",
      A4: "A4.mp3",
      A5: "A5.mp3",
      "A#5": "As5.mp3",
      B1: "B1.mp3",
      B2: "B2.mp3",
      B3: "B3.mp3",
      B4: "B4.mp3",
      "C#3": "Cs3.mp3",
      "C#4": "Cs4.mp3",
      "C#5": "Cs5.mp3",
      D2: "D2.mp3",
      D3: "D3.mp3",
      D5: "D5.mp3",
      "D#4": "Ds4.mp3",
      E2: "E2.mp3",
      E3: "E3.mp3",
      E4: "E4.mp3",
      E5: "E5.mp3",
      "F#2": "Fs2.mp3",
      "F#3": "Fs3.mp3",
      "F#4": "Fs4.mp3",
      "F#5": "Fs5.mp3",
      G3: "G3.mp3",
      G5: "G5.mp3",
      "G#2": "Gs2.mp3",
      "G#4": "Gs4.mp3",
      "G#5": "Gs5.mp3",
    },

    // Add more instruments and their samples as needed...
  },
};
